version: '3.8'

services:
  app:
    build: .
    container_name: thenest_app
    restart: unless-stopped
    environment:
      - MYSQL_HOST=thenest-db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=u559597593_thenest
    ports:
      - "8000:8000"
    depends_on:
      - thenest-db
    command: sh -c "php artisan websockets:serve --port=6001 & php artisan serve --host=0.0.0.0 --port=8000"
    networks:
      - thenest_network
    
  thenest-db:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: u559597593_thenest
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
      - ./custom.cnf:/etc/mysql/conf.d/custom.cnf
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
    networks:
      - thenest_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: thenest_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: thenest-db  # Corrected value
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - thenest-db
    networks:
      - thenest_network

volumes:
  mysql_data:

networks:
  thenest_network:
    driver: bridge